### ISSUE TITLE
关于lshort-zh-cn中bibtex的内容

### ISSUE THREAD

**Issue by ghost** [CTeX-org/lshort-cn#2]
在lshort-zh-cn中，bibtex的介绍内容有一些值得商榷。
1. plain模式下的例子可以稍作更改。目前的例子更像abbrv模式。
2. 使用natbib包时，应该改为plainnat模式才能进入author-year，否则还是以前的样子。这点在natbib的说明文档中有写。

**Comment by louisstuart96** [comment]
已在 dedc156 中修改。多谢！
