### ISSUE TITLE
5.1.4 字体编码一节关于连字符的叙述有误

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/lshort-cn#3]
在英文中很少使用波浪号作为连字符，所以 5.1.4 节中的 “a~b” 用法是错误的，包括 `\textasciitilde` 和 `\sim`。

https://en.wikipedia.org/wiki/Tilde
> In some languages (though not generally in English)[citation needed], a tilde-like wavy dash may be used as punctuation (instead of an unspaced hyphen or en-dash) between two numbers, to indicate a range rather than subtraction or a hyphenated number (such as a part number or model number). For example, "12~15" means "12 to 15", "3" means "up to three", and "100" means "100 and greater". Japanese and other East Asian languages almost always use this convention, but it is often done for clarity in some other languages as well. Chinese uses the wavy dash and full-width em dash interchangeably for this purpose. In English, the tilde is often used to express ranges and model numbers in electronics, but rarely in formal grammar or in type-set documents, as a wavy dash preceding a number sometimes represents an approximation (see below).

在中文里波浪号可以作为连字符表示范围，但是这个符号是 U+FF5E “～”。
https://zh.wikipedia.org/wiki/连接号

**Comment by louisstuart96** [comment]
这个可能有得商榷，在 https://en.wikipedia.org/wiki/Tilde#Punctuation 里说的是，有些西文也用这个波浪号表示范围，不过可能英文不太用？另外表示近似的用法还是很常见的，要不把后一种用法写上去好了。

**Comment by zepinglee** [comment]
目前 lshort-zh-cn 的描述仍然容易误导人。

![screen shot 2018-11-22 at 10 57 27 pm](https://user-images.githubusercontent.com/12290822/48910396-d0d0dc80-eeaa-11e8-956e-fdea81bfb562.png)

1. “有些西文也用这个波浪号表示范围”这个结论缺乏证据。而小林章的《西文字体》里说：
> 而“～”符号在西文里当数学符号用，并没有“从……到……”的意思。

所以不应该在 lshort 里写这样的用法，而应该指出正确的用法（en dash）。

2. 应该明确指出“有的人可能喜欢用数学公式里的 \sim 符号来代替”是错误的写法，“更合理的波浪号”的表述也让人误以为前一种写法还有合理性。示例更不应该写两个错误的示例“1~2, 1\sim 2”，应该给出正确的示例 U+FF5E “～”符号，目前提到的 5.1.4 节也没有提到波浪号。

**Comment by zepinglee** [comment]
Fandol 的 “～”（U+FF5E）字形顶部，建议不要使用 fandol。

**Comment by zepinglee** [comment]
表示“大约”的用法是放在数字前面，不是用在两个数字中间

**Comment by zepinglee** [comment]
我发现 1675bc6 的 commit 信息拼错了，最好 merge 到 mater 之前 rebase 一下

**Comment by louisstuart96** [comment]
字体的话，考虑到 Fandol 是全平台 TeX Live 都能用的，而使用 ctex 默认的 scheme 有各平台不一致之虞。

**Comment by zepinglee** [comment]
我个人认为字体本身的质量更重要，跨平台能编译通过就行

**Comment by Stone-Zeng** [comment]
我觉得普通文本的排版不应该借助数学公式来完成，在现代的环境中还是尽量用符合语义的 character 比较合适。所以最好就是用正文字体自带的 U+007E 或者 U+223C。

众所周知传统上 TeX 用了很多 hack 的手段（比如不区分 glyph 和 character，用 `\sim` 表示 tilde 这样），我们是不是可以考虑标注/说明一下？

**Comment by louisstuart96** [comment]
@zepinglee b618b00 把容易引起争论或误导的地方清理了一下，毕竟这个手册的重心不在于某个标点符号的争论上。如果有人坚持要用波浪号，也不好说啥。

**Comment by zepinglee** [comment]
1. 我没觉得这里有什么争议和误导。
2. 这个手册应该指导用户如何正确使用，而不是给用户错误的目标指一条路。
3. 1675bc6 的 commit 信息有错，最好 rebase 一下。

**Comment by louisstuart96** [comment]
这个改法应该基本上做到了“指导用户如何正确使用”吧，如果你同意这一点的话，这个 issue 就暂时告一段落。
