### ISSUE TITLE
使用粗斜体表示向量的叙述有误

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/lshort-cn#4]
@louisstuart96 
https://github.com/CTeX-org/lshort-cn/blob/d7230be36d0b6936d283ca438b46506d53bd0845/src/chap/chap.04.math.tex#L725

根据《GB 3102.11-1993 物理科学和技术中使用的数学符号》标准，
![screen shot 2018-06-17 at 12 20 54 pm](https://user-images.githubusercontent.com/12290822/41504677-ea97ffa8-7228-11e8-9d54-5a4110dc5094.png)
使用粗斜体表示向量是正确的用法，尤其用在在印刷。

**Comment by louisstuart96** [comment]
这标准，脑阔疼……

**Comment by zepinglee** [comment]
TeX 排版的数学公式默认是按照美国的习惯，向量和矩阵用粗正体，我国和 ISO 的标准是使用粗斜体。我稍微比较了一下，见 https://gist.github.com/zepinglee/806b7bad0d3fa3cbac9ba2aa83e0a9a7
