### ISSUE TITLE
Microsoft Word 习惯的页面设定

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/lshort-cn#5]
https://github.com/CTeX-org/lshort-cn/blob/32ad0638e23fc94b7d8c2236c00934920cf7d8c9/src/chap/chap.05.style.tex#L485

事实上，Microsoft Word 2003 及以前默认是上下边距 1.25 英寸，左右边距 1 英寸，这里写反了；

Microsoft Word 2003 及以后默认是边距一致为 1.25 英寸。

**Comment by louisstuart96** [comment]
不对吧，这是 Office 365 (2016) 的默认设置：
<img width="960" alt="off" src="https://user-images.githubusercontent.com/13765622/43672169-35eb375e-97db-11e8-987b-f7db87daef01.png">

**Comment by zepinglee** [comment]
啊我搞错了
